entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: "/certs/cert.pem"
      keyFile: "/certs/key.pem"

providers:
  docker: {}

api:
  dashboard: true